### Preprocessing all the 850 CFLIB stars spectra using preprocessing.py

In [2]:
import numpy as np
import pandas as pd 

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

Defining the path of the CFLIB data folder

In [3]:
folder_path = "/home/arbiter/IRAF"

raw_string = r"/home/arbiter/IRAF"

In [ ]:
import os

list_files = os.listdir(folder_path)        # creating a list of all the file names in the folder

print(list_files)
print(len(list_files))


['89125.fits', '115539.fits', '114038.fits', '214923.fits', '201889.fits', '115444.fits', 'G_101-29.fits', '191372.fits', '12929.fits', '61295.fits', '82621.fits', '160762.fits', '113092.fits', '206078.fits', '145502.fits', '178266.fits', '187929.fits', '148783.fits', '1967.fits', '196740.fits', '63410.fits', '151769.fits', '224533.fits', 'G_17-30.fits', '94363.fits', '111028.fits', '58343.fits', '169191.fits', '177940.fits', '188350.fits', '120452.fits', '125184.fits', '200790.fits', '219945.fits', '175535.fits', '159307.fits', 'G_122-51.fits', '59380.fits', '143761.fits', '3817.fits', '80493.fits', '206067.fits', '4963.fits', '73394.fits', '157373.fits', 'G_43-33.fits', '112142.fits', '190172.fits', '96436.fits', '83787.fits', '58855.fits', '75782.fits', '208202.fits', '216219.fits', '213660.fits', '83506.fits', '107328.fits', '104304.fits', '34797.fits', '198001.fits', '179761.fits', '190004.fits', '20902.fits', '143666.fits', '42543.fits', 'G_65-47.fits', '147700.fits', '34334.fits

loading the sharma et al 2020 preprocessed CFLIB data to select the 850 stars we want out of all the stars in the data:

In [ ]:
cflib_data_preprocessed = np.load("cflib_data.npz", allow_pickle= True)     

In [ ]:
cflib_data_preprocessed["fname"]        # Checking the order of the names

Retrieving the 850 stars

In [ ]:
stars = []

for j in cflib_data_preprocessed["fname"]:
    for i in list_files:
        if i == j:
            stars.append(i)

stars

In [ ]:
len(stars)

850

Preprocessing the selected stars using preprocessing.py in the same order as done in sharma et al preprocessed CFLIB

In [ ]:
import preprocessing

flux_arr = []

for i in stars:
    for j in list_files:
        if i == j:
            wavelength, flux = preprocessing.preprocess(f"/home/arbiter/IRAF/{i}")
            flux_arr.append(flux)
            
flux_arr

In [20]:
len(flux_arr)

850

Checking for the CFLIB preprocessed data for the 0th index star i.e. HD100889

In [12]:
flux_arr[0]

array([1.18421388, 1.18500031, 1.1858371 , ..., 0.41275552, 0.41242933,
       0.41237529], shape=(4306,))

In [14]:
cflib_data_preprocessed["flux"][0]

array([1.176708573333929, 1.1760512221903987, 1.173074399498486, ...,
       0.4122635493170717, 0.41270305790417994, 0.41297965237073375],
      shape=(4367,), dtype=object)

In [17]:
wave, flux_100889 = preprocessing.preprocess("/home/arbiter/IRAF/100889.fits")
flux_100889

array([1.18421388, 1.18500031, 1.1858371 , ..., 0.41275552, 0.41242933,
       0.41237529], shape=(4306,))

Loading the preprocessed flux data in a file :

In [ ]:
# np.save("preprocess_cflib_vyom.npy", flux_arr)